image:
  file: .ddev/.gitpod.Dockerfile

# ddev and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - init: |
      ddev start -y
      ddev composer install -d packages/docs/.symfony/
      npm install
      npm run docs:build
    command: |
      ddev start -y
      gp await-port 8080 && gp preview $(gp url 8080)
# VScode xdebug extension
vscode:
  extensions:
    # PHP extensions.
    - bmewburn.vscode-intelephense-client
    # Twig extensions.
    - mblode.twig-language-2

ports:
  # Used by ddev - local db clients
  - port: 3306
    onOpen: ignore
  # Used by projector
  - port: 6942
    onOpen: ignore
  # Used by MailHog
  - port: 8027
    onOpen: ignore
  # Used by phpMyAdmin
  - port: 8036
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # Ignore host https port
  - port: 8443
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
