twig:
    default_path: '%kernel.project_dir%/../ui/'
    paths:
        '%kernel.project_dir%/templates': private
        '%kernel.project_dir%/public/assets/svg': svg
        '%kernel.project_dir%/../ui/': ui

when@test:
    twig:
        strict_variables: true
